sudo: required
language: go
services:
- docker
install:
- docker pull therecipe/qt:linux
- go get -u -v github.com/therecipe/qt/cmd/...
- go get -u -v github.com/McKael/madon
script:
- "$GOPATH/bin/qtdeploy -docker build linux"
before_deploy: tar -czvf fedigo-linux.tar.gz deploy
deploy:
  provider: releases
  api_key:
    secure: DR+JdWwyW2+JLIWDeLBfwALla0su1DEBZqtGT2y1j7sIq/Z8b+GPpSdQOcw8C8DeD0dmHEGRDu8i4FD9ljf2jtKybKEAcXlg5K95MYnVZp7tHSjOCxYdCV5CnZbg7T8mfR6lo3VCt1bubOSPkOFbnjZ+KkzLPsOeU2VwWDJyN7lT+m3B9SCUoCBo3MNvL1wZeH2h18GZ+7EYRb3leCuL95rfc0qO/05oM9Yr72vMF/5lBp+RlzD4tTjjMbb6ZVl4SkuFDYxJ7sl+84VyF48rc5lmyYU+uKIbHauoefjyy71CNVKHSbOsvylYqurdPr0tupcB5dDIG7XJJFlccV3SppgOkdTtbL/bS7G3F1LJRAhxZTZ0peFTmITJd3IzdYT3syVUM9h1IG3iNkujAbZbz6C3PccrQI48o97sArmSIYs/LM+SYtaE8fIYUbEkxr0HuXt/tMhf2Z15KTVu7iIB9zETl9eBtbHzOedzBKF38mXjRUOrJuHgmxeyuW7KS75HfRZWkirlm1S3ZE4toIWT3bQp4TJrW0/nKOJhZ2lH95M/kRElVCAFsByKvjBWU0/4A16u6SC7fcpJRdNwr9blX92sqfekiUuZkrFh7P77KDwXFq0CCUhT1MEEZSHjIWnrqvEaAIfK1jCgJhJD9scb/aliXxNrM8n6l3IWcK96Rmk=
  file: fedigo-linux.tar.gz
  on:
    repo: anjandev/fedi-go
  skip_cleanup: true
  prerelease: true
  on:
    tags: true