sudo: required
language: go
services:
- docker

install:
- docker pull therecipe/qt:linux
- go get -u -v github.com/therecipe/qt/cmd/...
- go get -u -v github.com/McKael/madon

script:
- $GOPATH/bin/qtdeploy -docker build linux
